# Daemonium Configuration

# MongoDB Configuration
mongodb:
  host: localhost
  port: 27018
  database: daemonium
  username: admin
  password: ch@ng3m300
  
# PostgreSQL Configuration
postgresql:
  host: localhost
  port: 5433
  database: daemonium
  username: postgres
  password: postgres

# Qdrant Configuration
qdrant:
  host: localhost
  port: 6333
  grpc_port: 6334

# Neo4j Configuration
neo4j:
  host: localhost
  http_port: 7475
  bolt_port: 7688
  username: neo4j
  password: ch@ng3m300
  database: neo4j
  
# Application Settings
app:
  debug: false
  log_level: INFO