# Daemonium Configuration

# MongoDB Configuration
mongodb:
  host: localhost
  port: 27018
  database: daemonium
  username: admin
  password: ch@ng3m300
  
# PostgreSQL Configuration
postgresql:
  host: localhost
  port: 5433
  database: daemonium
  username: postgres
  password: postgres

# Qdrant Configuration
qdrant:
  host: localhost
  port: 6343
  grpc_port: 6344

# Neo4j Configuration (Enterprise Edition - Multiple Databases)
neo4j:
  host: localhost
  http_port: 7475
  bolt_port: 7688
  username: neo4j
  password: ch@ng3m300
  # Default database
  database: neo4j
  # Additional databases for comparison
  databases:
    primary: daemonium-primary    # Primary knowledge graph
    comparison: daemonium-comparison  # Comparison knowledge graph
    experimental: daemonium-experimental  # Experimental features
  
  # Script-specific database assignments (optional)
  script_databases:
    enhanced_neo4j_kg_build: daemonium-primary
    comparison_analysis: daemonium-comparison
    experimental_features: daemonium-experimental
  
# Redis Configuration
redis:
  host: localhost
  port: 6380
  password: ch@ng3m300
  db: 0
  
# Application Settings
app:
  debug: false
  log_level: INFO