# Example Firebase configuration (safe to commit)
# Copy to config/firebase.yaml and fill in real values. Do NOT commit firebase.yaml.

firebase:
  projectId: "YOUR_FIREBASE_PROJECT_ID"
  apiKey: "YOUR_FIREBASE_API_KEY"
  authDomain: "YOUR_FIREBASE_AUTH_DOMAIN"
  storageBucket: "YOUR_FIREBASE_STORAGE_BUCKET"
  messagingSenderId: "YOUR_FIREBASE_MESSAGING_SENDER_ID"
  appId: "YOUR_FIREBASE_APP_ID"
  measurementId: "YOUR_FIREBASE_MEASUREMENT_ID"

  auth:
    providers:
      google: true
      email: false
      github: false

  emulator:
    enabled: false
